---
  - name: Download theo-agent from github
    get_url:
      url: https://github.com/theoapp/theo-agent/releases/download/{{ theoagent_version }}/theo-agent-linux-{{ theoagent_arch }}
      dest: /usr/sbin/theo-agent
      mode: 0775

  - name: Add user {{ theoagent_user }}
    user:
      name: "{{ theoagent_user }}"
      create_home: false
      system: true
      comment: Theo Agent
      shell: /bin/false

  - name: Create theo-agent settings folder
    file:
      path: /etc/theo-agent/
      owner: "{{ theoagent_user }}"
      group: root
      state: directory

  - name: Create theo-agent cache folder
    file:
      path: /var/cache/theo-agent/
      owner: "{{ theoagent_user }}"
      group: root
      mode: 0755
      state: directory

  - name: Copy public.pem if theo_public_key_path is defined
    copy:
      src: public.pem
      dest: "{{ theo_public_key_path }}"
      mode: 0640
      owner: "{{ theoagent_user }}"
      group: root
    when: 
      - theo_public_key_path is defined

  - name: Create theo-agent config
    template:
      src: config.yml
      dest: /etc/theo-agent/config.yml

  - name: Check sshd_config for PasswordAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      insertafter: '^#PasswordAuthentication'
      line: 'PasswordAuthentication no'

  - name: Check sshd_config for AuthorizedKeysFile
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AuthorizedKeysFile'
      insertafter: '^#AuthorizedKeysFile'
      line: 'AuthorizedKeysFile /var/cache/theo-agent/%u'

  - name: Check sshd_config for AuthorizedKeysCommand
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AuthorizedKeysCommand'
      insertafter: '^#AuthorizedKeysCommand'
      line: 'AuthorizedKeysCommand /usr/sbin/theo-agent {{ theoagent_akc_params | default("")}}'

  - name: Check sshd_config for AuthorizedKeysCommandUser
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AuthorizedKeysCommandUser'
      insertafter: '^#AuthorizedKeysCommandUser'
      line: 'AuthorizedKeysCommandUser {{ theoagent_user }}'

  - name: reload service ssh, in all cases
    systemd:
      name: ssh
      state: reloaded
